# Generated by Django 3.1 on 2021-01-11 06:08

from django.db import migrations, models
import django.db.models.deletion
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20210111_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_companies', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_companies', to='employees.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.employee_photo_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo_card',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.employee_photo_path),
        ),
    ]
