# Generated by Django 3.1 on 2021-01-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bot_token',
        ),
    ]
