# Generated by Django 3.1 on 2021-01-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_company_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
