# Generated by Django 3.1 on 2021-01-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfirmation',
            name='notified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
