# Generated by Django 3.1 on 2021-01-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_taskconfirmation_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employees_notified',
        ),
    ]
