# Generated by Django 3.1 on 2021-01-25 19:13

from django.db import migrations, models
import task_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_remove_task_employees_notified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=task_management.models.tasks_photo_path),
        ),
    ]
