# Generated by Django 3.1 on 2021-01-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_auto_20210126_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-id',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
