# Generated by Django 3.1 on 2021-02-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20210126_0056'),
        ('task_management', '0005_auto_20210127_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employees_to_notify',
            field=models.ManyToManyField(blank=True, related_name='tasks_in_notification', to='employees.Employee'),
        ),
    ]
