# Generated by Django 3.1 on 2020-08-25 17:29

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='time_management.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate, editable=False)),
                ('absent', models.BooleanField(default=False)),
                ('absence_excuse', models.TextField(blank=True, null=True)),
                ('pauses', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateRangeField(), size=None)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('absent', 'Отсуствует'), ('working', 'В работе'), ('paused', 'Приостановлен'), ('finished', 'Завершен')], default='new', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='time_management.employee')),
            ],
        ),
    ]
