# Generated by Django 3.1 on 2021-03-02 10:05

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenseExcuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Причина отсуствия',
                'verbose_name_plural': 'Причины отсуствия',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='Даты С-По')),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Праздники',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HolidayMoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_from', models.DateField(verbose_name='Перенесен с')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_management.holiday', verbose_name='Праздник')),
            ],
            options={
                'verbose_name': 'Перенесенная дата',
                'verbose_name_plural': 'Перенесенные даты',
            },
        ),
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate, editable=False)),
                ('absent', models.BooleanField(default=False)),
                ('pauses', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('absent', 'Отсуствует'), ('working', 'В работе'), ('finished', 'Завершен')], default='new', max_length=20)),
                ('absence_excuse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='time_management.absenseexcuse')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность сотрудника',
                'verbose_name_plural': 'Активность сотрудников',
                'ordering': ('-date',),
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
