# Generated by Django 3.1 on 2020-08-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
