# Generated by Django 3.1 on 2020-08-25 18:00

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0002_auto_20200825_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeactivity',
            name='pauses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True), size=None),
        ),
    ]
