# Generated by Django 3.1 on 2020-11-24 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0005_auto_20201124_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeactivity',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
    ]
