# Generated by Django 3.1 on 2020-12-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0006_auto_20201124_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeactivity',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('absent', 'Отсуствует'), ('working', 'В работе'), ('finished', 'Завершен')], default='new', max_length=20),
        ),
    ]
