# Generated by Django 3.1 on 2020-12-27 07:34

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0008_auto_20201227_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='Даты С-По')),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Праздники',
            },
        ),
        migrations.CreateModel(
            name='HolidayMoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_from', models.DateField(verbose_name='Перенесен с')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_management.holiday', verbose_name='Праздник')),
            ],
            options={
                'verbose_name': 'Перенесенная дата',
                'verbose_name_plural': 'Перенесенные даты',
            },
        ),
    ]
