# Generated by Django 3.1 on 2021-01-11 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20201227_1305'),
        ('time_management', '0009_holiday_holidaymoved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeactivity',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='employees.employee'),
        ),
    ]
