# Generated by Django 3.1 on 2021-01-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20201227_1305'),
        ('time_management', '0010_auto_20210111_1053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeactivity',
            unique_together={('employee', 'date')},
        ),
    ]
