# Generated by Django 3.1 on 2021-01-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0011_auto_20210111_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeactivity',
            options={'ordering': ('-date',), 'verbose_name': 'Активность сотрудника', 'verbose_name_plural': 'Активность сотрудников'},
        ),
    ]
