# Generated by Django 3.1 on 2021-02-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0012_auto_20210111_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenseExcuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Причины отсуствия',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='absence_excuse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='time_management.absenseexcuse'),
        ),
    ]
