# Generated by Django 3.1 on 2021-02-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0013_auto_20210207_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absenseexcuse',
            options={'ordering': ('-id',), 'verbose_name': 'Причина отсуствия', 'verbose_name_plural': 'Причины отсуствия'},
        ),
    ]
