# Generated by Django 3.1 on 2021-03-02 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_employees', models.BooleanField(default=False)),
                ('employees_notified', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=news_management.models.news_photo_path)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news', to=settings.AUTH_USER_MODEL)),
                ('employees_to_notify', models.ManyToManyField(blank=True, related_name='news_in_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-id',),
            },
        ),
    ]
