# Generated by Django 3.1 on 2021-01-25 18:56

from django.db import migrations, models
import django.db.models.deletion
import news_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0010_auto_20210126_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_employees', models.BooleanField(default=False)),
                ('employees_notified', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=news_management.models.news_photo_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_news', to='employees.employee')),
                ('employees_to_notify', models.ManyToManyField(related_name='news_in_notification', to='employees.Employee')),
            ],
        ),
    ]
