# Generated by Django 3.1 on 2021-03-02 10:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('code', models.CharField(db_index=True, editable=False, max_length=12, verbose_name='OTP')),
                ('verified', models.BooleanField(default=False, editable=False, verbose_name='Подтверждён')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(editable=False, max_length=128, region=None, verbose_name='Мобильный телефон')),
            ],
            options={
                'verbose_name': 'Одноразовый пароль',
                'verbose_name_plural': 'Одноразовые пароли',
                'unique_together': {('code', 'phone')},
            },
        ),
    ]
