# Generated by Django 3.1 on 2021-03-02 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import event_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('all_employees', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('place', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=event_management.models.events_photo_path)),
                ('telegram_group_link', models.URLField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('employees_to_notify', models.ManyToManyField(blank=True, related_name='events_in_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие/Встреча',
                'verbose_name_plural': 'События/Встречи',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='EventDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=event_management.models.events_photo_path)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='event_management.event')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='EventConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(blank=True, default=False, null=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_confirmations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='event_management.event')),
            ],
        ),
    ]
