# Generated by Django 3.1 on 2021-01-11 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_remove_company_bot_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_employees', models.BooleanField(default=False)),
                ('employees_notified', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='employees.employee')),
                ('notify_employees', models.ManyToManyField(related_name='employees', to='employees.Employee')),
            ],
        ),
    ]
