# Generated by Django 3.1 on 2021-01-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-id',), 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
