# Generated by Django 3.1 on 2021-01-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_auto_20210111_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-id',), 'verbose_name': 'Событие/Встреча', 'verbose_name_plural': 'События/Встречи'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='notify_employees',
            new_name='employees_to_notify',
        ),
        migrations.AddField(
            model_name='event',
            name='force_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
