# Generated by Django 3.1 on 2021-01-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_auto_20210111_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
