# Generated by Django 3.1 on 2021-01-25 19:13

from django.db import migrations, models
import event_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0007_auto_20210126_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=event_management.models.events_photo_path),
        ),
    ]
