# Generated by Django 3.1 on 2021-02-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0009_eventdocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='telegram_group_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
